FROM node:lts-alpine

ENV HOST=0.0.0.0
ENV NODE_ENV=development

WORKDIR /app

COPY ./container/dev/entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 3000
EXPOSE 9095

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
